###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = "Henrik Finsberg og Kristian Hustad"
comments_config = {"hypothesis": False, "utterances": False}
copyright = "2025"
exclude_patterns = [
    "**.ipynb_checkpoints",
    ".DS_Store",
    ".github/*",
    ".pytest_cache/*",
    "Thumbs.db",
    "_build",
    "**.jupyter_cache",
]
extensions = [
    "sphinx_togglebutton",
    "sphinx_copybutton",
    "myst_nb",
    "jupyter_book",
    "sphinx_thebe",
    "sphinx_comments",
    "sphinx_external_toc",
    "sphinx.ext.intersphinx",
    "sphinx_design",
    "sphinx_book_theme",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_jupyterbook_latex",
    "sphinx_multitoc_numbering",
]
external_toc_exclude_missing = True
external_toc_path = "_toc.yml"
html_baseurl = ""
html_favicon = ""
html_last_updated_fmt = "%b %d, %Y"
html_logo = "docs/logo.png"
html_sourcelink_suffix = ""
html_theme = "sphinx_book_theme"
html_theme_options = {
    "search_bar_text": "Search this book...",
    "launch_buttons": {
        "notebook_interface": "classic",
        "binderhub_url": "",
        "jupyterhub_url": "",
        "thebe": True,
        "colab_url": "",
        "deepnote_url": "",
    },
    "path_to_docs": "docs",
    "repository_url": "https://github.com/ComputationalPhysiology/ap_features",
    "repository_branch": "main",
    "extra_footer": "",
    "home_page_in_toc": True,
    "announcement": "",
    "analytics": {
        "google_analytics_id": "",
        "plausible_analytics_domain": "",
        "plausible_analytics_url": "https://plausible.io/js/script.js",
    },
    "use_repository_button": True,
    "use_edit_page_button": False,
    "use_issues_button": True,
}
html_title = "Action potential features"
latex_engine = "pdflatex"
myst_enable_extensions = ["amsmath", "dollarmath", "linkify"]
myst_url_schemes = ["mailto", "http", "https"]
nb_execution_allow_errors = False
nb_execution_cache_path = ""
nb_execution_excludepatterns: list[str] = []
nb_execution_in_temp = False
nb_execution_mode = "cache"
nb_execution_timeout = 30
nb_output_stderr = "show"
numfig = True
pygments_style = "sphinx"
suppress_warnings = ["myst.domains"]
use_jupyterbook_latex = True
use_multitoc_numbering = True
