# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Action potential features
author: Henrik Finsberg og Kristian Hustad
logo: logo.png
copyright: "2021"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  thebe: true

# Information about where the book exists on the web
repository:
  url: https://github.com/ComputationalPhysiology/ap_features # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: <a href="https://www.simula.no/research/projects/department-computational-physiology">Computational Physiology at Simula</a>

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
