name: Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          make dev
      - name: Lint with flake8
        run: |
          make lint
      - name: Type checking with mypy
        run: |
          make type
      - name: Test with pytest
        run: |
          make test
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage.xml
      - name: Coverage report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
